CHECKPOINT_DIR: "/snel/share/joel/transformer_modeling/"
DATA:
  DATAPATH: "/snel/share/data/ndt_paper/m1_maze/heldout_trial/2296_trials/0_seed"
  TRAIN_FILENAME: 'lfads_input.h5'
  VAL_FILENAME: 'lfads_input.h5'
MODEL:
  TRIAL_LENGTH: 70
  LEARNABLE_POSITION: True
  PRE_NORM: True
  FIXUP_INIT: True
  EMBED_DIM: 0
  LOGRATE: True
TRAIN:
  LR:
    WARMUP: 5000
  MASK_RATIO: 0.25
  WEIGHT_DECAY: 5.0e-05
  PATIENCE: 3000
  LOG_INTERVAL: 200
  VAL_INTERVAL: 20
  CHECKPOINT_INTERVAL: 1000
  NUM_UPDATES: 50501
  MASK_SPAN_RAMP_START: 8000
  MASK_SPAN_RAMP_END: 12000

  TUNE_HP_JSON: './configs/20ms_arxiv.json' # This space has more aggressive regularization
