CHECKPOINT_DIR: "./ckpts/dmfc_rsg/"
TENSORBOARD_DIR: "./tb/dmfc_rsg/"
LOG_DIR: "./logs/dmfc_rsg/"
DATA:
  DATAPATH: "./data/"
  TRAIN_FILENAME: 'dmfc_rsg_full.h5'
  VAL_FILENAME: 'dmfc_rsg_full.h5'
MODEL:
  TRIAL_LENGTH: 0
  LEARNABLE_POSITION: False
  POSITION:
    OFFSET: False
  PRE_NORM: True
  FIXUP_INIT: True
  EMBED_DIM: 1
  LOGRATE: True
  NUM_LAYERS: 6
  NUM_HEADS: 2
  LINEAR_EMBEDDER: True
  USE_CONTRAST_PROJECTOR: False
  CONTRAST_LAYER: 'embedder'
  LAMBDA: 1e-1
TRAIN:
  LR:
    WARMUP: 5000
  MASK_RATIO: 0.25
  WEIGHT_DECAY: 5.0e-05
  PATIENCE: 4000
  LOG_INTERVAL: 200
  VAL_INTERVAL: 20
  CHECKPOINT_INTERVAL: 1000
  NUM_UPDATES: 50501
  MASK_SPAN_RAMP_START: 8000
  MASK_SPAN_RAMP_END: 12000
  MASK_MODE: "full"
  DO_CONTRAST: True
  CONTRAST_MASK_MODE: "full"
  CONTRAST_MASK_RATIO: 0.05
  CONTRAST_MASK_TOKEN_RATIO: 0.5
  CONTRAST_MASK_RANDOM_RATIO: 0.5
  CONTRAST_MASK_SPAN_RAMP_START: 8000
  CONTRAST_MASK_SPAN_RAMP_END: 12000

  TUNE_HP_JSON: './configs/dmfc_rsg.json' # This space has more aggressive regularization