# Author: Joel Ye
# Orginal file available at https://github.com/snel-repo/neural-data-transformers/blob/master/configs/mc_maze.yaml
# Adapted by Trung Le
# Modified configs for STNDT

CHECKPOINT_DIR: "./ckpts/mc_maze_20/"
TENSORBOARD_DIR: "./tb/mc_maze_20/"
LOG_DIR: "./logs/mc_maze_20/"

DATA:
  DATAPATH: "/home/kabird/datasets/"
  TRAIN_FILENAME: "mc_maze_20_full.h5"
  VAL_FILENAME: "mc_maze_20_full.h5"

MODEL:
  TRIAL_LENGTH: 0
  LEARNABLE_POSITION: False
  POSITION:
    OFFSET: False
  PRE_NORM: True
  FIXUP_INIT: True
  EMBED_DIM: 1
  LOGRATE: True
  NUM_LAYERS: 4
  NUM_HEADS: 1
  LINEAR_EMBEDDER: True
  USE_CONTRAST_PROJECTOR: False
  CONTRAST_LAYER: 'embedder'
  LAMBDA: 1e-1
  LINEAR_PROJECTOR: True

TRAIN:
  LR:
    WARMUP: 5000
  MASK_RATIO: 0.25
  WEIGHT_DECAY: 5.0e-05
  PATIENCE: 1 #3000
  LOG_INTERVAL: 20 #200
  VAL_INTERVAL: 20
  CHECKPOINT_INTERVAL: 1000
  NUM_UPDATES: 50501
  MASK_SPAN_RAMP_START: 8000
  MASK_SPAN_RAMP_END: 12000
  MASK_MODE: "full"
  DO_CONTRAST: True
  CONTRAST_MASK_MODE: "full"
  CONTRAST_MASK_RATIO: 0.05
  CONTRAST_MASK_TOKEN_RATIO: 0.5
  CONTRAST_MASK_RANDOM_RATIO: 0.5
  CONTRAST_MASK_SPAN_RAMP_START: 8000
  CONTRAST_MASK_SPAN_RAMP_END: 12000

  TUNE_HP_JSON: "./configs/mc_maze_20.json"
